// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function Calcular(arg1:domain.Jornada):Promise<domain.Resultado>;

export function Cargar(arg1:string):Promise<domain.Jornada>;

export function FechasGuardadas():Promise<Array<string>>;

export function Guardar(arg1:domain.Jornada):Promise<void>;

export function Historial():Promise<Array<string>>;

export function Nueva(arg1:string):Promise<domain.Jornada>;

export function ObtenerEstadisticas(arg1:string):Promise<domain.Estadisticas>;
