// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Calcular(arg1) {
  return window['go']['main']['App']['Calcular'](arg1);
}

export function Cargar(arg1) {
  return window['go']['main']['App']['Cargar'](arg1);
}

export function FechasGuardadas() {
  return window['go']['main']['App']['FechasGuardadas']();
}

export function Guardar(arg1) {
  return window['go']['main']['App']['Guardar'](arg1);
}

export function Historial() {
  return window['go']['main']['App']['Historial']();
}

export function Nueva(arg1) {
  return window['go']['main']['App']['Nueva'](arg1);
}

export function ObtenerEstadisticas(arg1) {
  return window['go']['main']['App']['ObtenerEstadisticas'](arg1);
}
